[mongodb]
mongodb.devops26.sbs
[catalogue]
catalogue.devops26.sbs
[frontend]
frontend.devops26.sbs
[redis]
redis.devops26.sbs
[user]
user.devops26.sbs
[cart]
cart.devops26.sbs
[shipping]
shipping.devops26.sbs
[rabbitmq]
rabbitmq.devops26.sbs
[payment]
payment.devops26.sbs  
[all:vars]
ansible_username=ec2-user
ansible_password=DevOps321
