- name: stop "{{ component }}" service
  ansible.builtin.service:
    name: "{{ component }}"
    state: stopped
- name: remove old code of "{{ component }}" application
  ansible.builtin.file:
    path: /app
    state: absent
- name: download new code of "{{ component }}" application 
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v{{ app-version }}.zip
    dest: /app
    remote_src: yes
- name: install depencies
  community.general.npm:
    path: /app
- name: retstart {{ component }} service
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted

